### ISSUE TITLE
[Feature] K8S Secrets 添加 annotations

### ISSUE THREAD

**Issue by aazf** [usual2970/certimate#226]
**功能描述**

可以在k8s secrets添加证书的metadata 作为annotations属性来标识证书信息

**动机**

方便管理证书以及查看证书信息

**其他信息**

参考cert-manager

```
metadata:
  annotations:
    cert-manager.io/alt-names: demo.io,*.demo.io
    cert-manager.io/certificate-name: demo-cert
    cert-manager.io/common-name: demo.io
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: selfsigned
  ```
**建议**

```
metadata:
  annotations:
    certimate/alt-names: demo.io,*.demo.io
    certimate/certificate-name: demo-cert
    certimate/common-name: demo.io
    certimate/issuer-name: "certimate server name."
  ```

@fudiwei  @usual2970
