### ISSUE TITLE
希望docker镜像预置curl命令

### ISSUE THREAD

**Issue by geneives233** [usual2970/certimate#616]
### 功能描述 / Description

有些证书部署是通过http请求部署的，希望添加curl命令。

### 请求动机 / Motivation

扩大证书部署范围

### 贡献 / Contribution

- [ ] 我乐意为此贡献代码！ / I am interested in contributing to this feature!

**Comment by fudiwei** [comment]
可以自行安装。

**Comment by geneives233** [comment]
主要是不想要每次更新之后都去运行下apk add --no-cache curl命令

**Comment by fudiwei** [comment]
本地部署？你可以把安装依赖作为前置命令：

```sh
if ! command -v curl >/dev/null 2>&1; then
    apk add --no-cache curl
fi
```

**Comment by geneives233** [comment]
ok

**Comment by trashblazer** [comment]
个人实践：重新包装 entrypoint

`docker-compose.yml` 同目录下建一个 `entrypoint.sh` 写脚本。记得 `chmod +x entrypoint.sh`

```sh
#!/bin/sh
if ! command -v curl >/dev/null 2>&1; then
        sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
        apk add --no-cache curl
fi

./certimate serve --http 0.0.0.0:8090
```

`docker-compose.yml` 声明entrypoint

```yml
services:
  certimate:
    image: certimate/certimate:v0.3.18
    container_name: certimate
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/pb_data
      - ./entrypoint.sh:/app/entrypoint.sh
    entrypoint: /app/entrypoint.sh
```

curl 用来调用其他 http hook、socket，还是很实用，建议预置。
