### ISSUE TITLE
证书流水线自动的情况下会卡住，但手动执行又是正常的

### ISSUE THREAD

**Issue by MuXia-0326** [usual2970/certimate#769]
### 软件版本 / Release Version

 v0.3.16

### 问题描述 / Description

docker方式部署的
```yaml
services:
  certimate:
    image: usual2970/certimate:latest
    container_name: certimate_server
    ports:
      - 8090:8090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/pb_data
    restart: unless-stopped
```

自动执行的会卡在这一步
![Image](https://github.com/user-attachments/assets/cccfc411-0d14-4455-b4e2-e8764c1aa7d3)

手动执行的正常的
![Image](https://github.com/user-attachments/assets/adfaadb0-aeba-45ed-bdde-159f06fce5b9)
